version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install
      - run:
          name: run tests
          command: |
            pipenv run "nosetests ."
          
    