version: 2
jobs:
  building:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: install dependencies
          command: |
            pip install pipenv
            mkdir ~/bin
            cp /usr/local/bin/pipenv ~/bin/pipenv
            if [[ "$(ls -A /home/circleci/.local/share/virtualenvs)" ]]; then 
              echo "Use cache env" 
            else 
              ~/bin/pipenv install -d 
            fi
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/home/circleci/.local/share/virtualenvs"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - persist_to_workspace:
          root: ~/
          paths:
            - .

  test1:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: run tests
          command: |
            export PATH=~/.local/share/virtualenvs/project-zxI9dQ-Q/bin
            pipenv run "nosetests -q -s tests.test_my_module"

  test2:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: run tests
          command: |
            export PATH=~/.local/share/virtualenvs/project-zxI9dQ-Q/bin
            pipenv run "nosetests -q -s tests.test_my_module_2"

workflows:
  version: 2
  all:
    jobs:
      - building
      - test1:
          requires:
            - building
      - test2:
          requires:
            - building
          
    